In [1]:
import pandas as pd


df_quant = pd.read_csv("/Users/delser/Desktop/PhD/Phytochemistry/FBMN/alltissues/FEATURE-BASED-MOLECULAR-NETWORKING-cf822b6c-15072021/alltissues15072021-quant-py-dil.csv",index_col='row ID', sep=",")

df_motif = pd.read_csv("/Users/delser/Desktop/PhD/Phytochemistry/FBMN/alltissues/FEATURE-BASED-MOLECULAR-NETWORKING-cf822b6c-15072021/MS2LDA-all.csv",index_col='row ID', sep=",")

df_frag=pd.read_csv("/Users/delser/Desktop/PhD/Phytochemistry/FBMN/alltissues/FEATURE-BASED-MOLECULAR-NETWORKING-cf822b6c-15072021/MS2LDA-fragments.csv",index_col='Motif', sep=",")

In [2]:
df_frag.head()

                                     Feature   Min m/z   Max m/z  Probability
Motif
rhabdus_motif_95.m2m       fragment_100.0725  100.0700  100.0750        0.189
urine_mass2motif_27.m2m    fragment_100.0775  100.0750  100.0800        0.800
rhabdus_motif_250.m2m      fragment_100.1125  100.1100  100.1150        0.347
StrepSalini_motif_233.m2m  fragment_100.1500  100.1475  100.1525        0.117
rhamn_motif_163.m2m        fragment_101.0225  101.0200  101.0250        0.936

In [3]:
df_motif.head()
df_motif_red=df_motif.drop(["Precursor Mass","Retention Time","Document Annotation","Document","Probability","Overlap Score"], axis=1)

df_motif_red.head()

                    Motif
row ID
1               motif_433
1               motif_591
1               motif_502
1       gnps_motif_43.m2m
2               motif_433

In [4]:
#result= pd.concat([df_quant, df_motif.reindex(df_quant.index)], axis=1)
#result = pd.concat([df_quant, df_motif], ignore_index=True, sort=False)
result = df_quant.join(df_motif, how="outer")
#result = left.join(right, how="outer")
result.head()

,row m/z,row retention time,07 Nrep,07 Nnes,07 Nrxs,07 Nsto,07 Ntab,08 Nglu,10 Nben,10 Ncle,...,Solvent_RA5,Solvent_RA26,Solvent_RA7,Document,Motif,Probability,Overlap Score,Precursor Mass,Retention Time,Document Annotation
row ID,,,,,,,,,,,,,,,,,,,,,
1,375.300874,26.591875,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.00,...,0.0,0.000,0.000,1,motif_433,0.579,0.791,375.3009,None,None
1,375.300874,26.591875,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.00,...,0.0,0.000,0.000,1,motif_591,0.164,0.183,375.3009,None,None
1,375.300874,26.591875,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.00,...,0.0,0.000,0.000,1,motif_502,0.111,0.603,375.3009,None,None
1,375.300874,26.591875,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.00,...,0.0,0.000,0.000,1,gnps_motif_43.m2m,0.102,0.938,375.3009,None,None
2,375.300905,26.708085,139982614.0,79824894.67,0.0,113537839.7,60783.356,0.0,0.0,2594.56,...,0.0,1149.405,2550.285,2,motif_433,0.727,0.813,375.3009,None,None

In [5]:
clean=result.drop(["Precursor Mass","Retention Time","Document Annotation","Document"], axis=1)

In [6]:
#clean=clean.reset_index()

#full=result = df_quant.join(df_motif, how="outer")

In [7]:
#clean=clean.set_index("Motif")
#clean.head()

In [8]:
#full = clean.join(df_frag, how="outer")
#full.head()

In [9]:
#full.to_csv("alltissues27042021_all.csv",sep=',')

In [10]:
#occur = full.groupby(['Motif', 'row ID']).size()

#occur.head()

In [11]:
#occur.to_csv("alltissues27042021_counts.csv",sep=',')

In [12]:
occur1 = clean.groupby(['Motif', 'row ID']).size()

occur1.head()
clean.head()
#df.groupby(by=df.columns, axis=1).sum()

,row m/z,row retention time,07 Nrep,07 Nnes,07 Nrxs,07 Nsto,07 Ntab,08 Nglu,10 Nben,10 Ncle,...,Solvent_RA2,Solvent_RA3,Solvent_RA4,-Natt03-Caly,Solvent_RA5,Solvent_RA26,Solvent_RA7,Motif,Probability,Overlap Score
row ID,,,,,,,,,,,,,,,,,,,,,
1,375.300874,26.591875,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.00,...,0.0,0.0,0.0000,0.0000,0.0,0.000,0.000,motif_433,0.579,0.791
1,375.300874,26.591875,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.00,...,0.0,0.0,0.0000,0.0000,0.0,0.000,0.000,motif_591,0.164,0.183
1,375.300874,26.591875,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.00,...,0.0,0.0,0.0000,0.0000,0.0,0.000,0.000,motif_502,0.111,0.603
1,375.300874,26.591875,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.00,...,0.0,0.0,0.0000,0.0000,0.0,0.000,0.000,gnps_motif_43.m2m,0.102,0.938
2,375.300905,26.708085,139982614.0,79824894.67,0.0,113537839.7,60783.356,0.0,0.0,2594.56,...,0.0,0.0,546.6165,140.1965,0.0,1149.405,2550.285,motif_433,0.727,0.813

In [13]:
new=pd.get_dummies(df_motif_red, columns=['Motif'])
new.head()
#new.to_csv("counts-motif.csv",sep=',')

,Motif_StrepSalini_motif_10.m2m,Motif_StrepSalini_motif_105.m2m,Motif_StrepSalini_motif_106.m2m,Motif_StrepSalini_motif_108.m2m,Motif_StrepSalini_motif_110.m2m,Motif_StrepSalini_motif_113.m2m,Motif_StrepSalini_motif_119.m2m,Motif_StrepSalini_motif_128.m2m,Motif_StrepSalini_motif_144.m2m,Motif_StrepSalini_motif_168.m2m,...,Motif_urine_mass2motif_68.m2m,Motif_urine_mass2motif_78.m2m,Motif_urine_mass2motif_80.m2m,Motif_urine_mass2motif_83.m2m,Motif_urine_mass2motif_88.m2m,Motif_urine_mass2motif_90.m2m,Motif_urine_mass2motif_93.m2m,Motif_urine_mass2motif_94.m2m,Motif_urine_mass2motif_95.m2m,Motif_urine_mass2motif_97.m2m
row ID,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
#df_bool=new.drop_duplicates(subset=["row m/z"])
#df_bool.head()
#df_bool.to_csv("counts-motif-dupl.csv",sep=',')

In [15]:
#x=new.groupby(level=0)['row ID'].sum().reset_index()
x=new.groupby(new.index).sum()
x.head()

#y=x.transpose()
a=df_quant.drop(["row m/z","row retention time"], axis=1)
#a=a.transpose()

#y.head()

In [16]:
#a.head()
x.head()
#x.to_csv("counts-motif.csv",sep=',')

,Motif_StrepSalini_motif_10.m2m,Motif_StrepSalini_motif_105.m2m,Motif_StrepSalini_motif_106.m2m,Motif_StrepSalini_motif_108.m2m,Motif_StrepSalini_motif_110.m2m,Motif_StrepSalini_motif_113.m2m,Motif_StrepSalini_motif_119.m2m,Motif_StrepSalini_motif_128.m2m,Motif_StrepSalini_motif_144.m2m,Motif_StrepSalini_motif_168.m2m,...,Motif_urine_mass2motif_68.m2m,Motif_urine_mass2motif_78.m2m,Motif_urine_mass2motif_80.m2m,Motif_urine_mass2motif_83.m2m,Motif_urine_mass2motif_88.m2m,Motif_urine_mass2motif_90.m2m,Motif_urine_mass2motif_93.m2m,Motif_urine_mass2motif_94.m2m,Motif_urine_mass2motif_95.m2m,Motif_urine_mass2motif_97.m2m
row ID,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
#esult_bool = df_quant.join(x, how="outer")
#result_bool.head()
a.head()

,07 Nrep,07 Nnes,07 Nrxs,07 Nsto,07 Ntab,08 Nglu,10 Nben,10 Ncle,10 Ngla,10 Nnes,...,-Ncle03-Caly,Solvent_RA1,-Nben03-Caly,Solvent_RA2,Solvent_RA3,Solvent_RA4,-Natt03-Caly,Solvent_RA5,Solvent_RA26,Solvent_RA7
row ID,,,,,,,,,,,,,,,,,,,,,
1465,1912255.595,1819513.95,193807.138,1134014.55,225382.0585,169589.5770,128196.2975,87604.5795,175419.9760,172234.369,...,0.000000e+00,569.1535,249.555,0.0000,885.5805,656.0620,8.086200e+02,0.0000,263.604,134.2345
11687,2979.690,0.00,399.556,0.00,1295.0300,0.0000,139611.8360,130091.3065,285.3360,0.000,...,0.000000e+00,0.0000,1368.220,0.0000,1294.2630,4001.5840,2.439269e+03,1378.2065,0.000,342.2805
23160,0.000,1289.97,599.280,0.00,780.6560,338.1000,1953.2210,2100.7460,369.0195,0.000,...,8.149567e+05,0.0000,2656672.966,154.5080,792.4800,0.0000,1.003830e+06,795.6285,152.646,699.4875
13348,0.000,804.72,0.000,4006.46,18954.3080,37212.5555,173275.2150,421706.8330,7910.1925,0.000,...,2.044090e+06,0.0000,1737524.104,12516.2695,2254.5635,2145.2640,1.358149e+06,0.0000,9782.190,5743.9425
30656,0.000,0.00,0.000,0.00,999.4080,536.3860,5039.4610,53901.9645,0.0000,120.170,...,3.916763e+06,0.0000,1315696.120,3870.7565,2773.6960,3490.2665,2.066143e+06,2644.5225,3030.446,1771.9900

In [18]:
quant0=a.where(a >10000,0) 
quant0.head()

,07 Nrep,07 Nnes,07 Nrxs,07 Nsto,07 Ntab,08 Nglu,10 Nben,10 Ncle,10 Ngla,10 Nnes,...,-Ncle03-Caly,Solvent_RA1,-Nben03-Caly,Solvent_RA2,Solvent_RA3,Solvent_RA4,-Natt03-Caly,Solvent_RA5,Solvent_RA26,Solvent_RA7
row ID,,,,,,,,,,,,,,,,,,,,,
1465,1912255.595,1819513.95,193807.138,1134014.55,225382.0585,169589.5770,128196.2975,87604.5795,175419.976,172234.369,...,0.000000e+00,0.0,0.000,0.0000,0.0,0.0,0.000,0.0,0.0,0.0
11687,0.000,0.00,0.000,0.00,0.0000,0.0000,139611.8360,130091.3065,0.000,0.000,...,0.000000e+00,0.0,0.000,0.0000,0.0,0.0,0.000,0.0,0.0,0.0
23160,0.000,0.00,0.000,0.00,0.0000,0.0000,0.0000,0.0000,0.000,0.000,...,8.149567e+05,0.0,2656672.966,0.0000,0.0,0.0,1003829.751,0.0,0.0,0.0
13348,0.000,0.00,0.000,0.00,18954.3080,37212.5555,173275.2150,421706.8330,0.000,0.000,...,2.044090e+06,0.0,1737524.104,12516.2695,0.0,0.0,1358149.409,0.0,0.0,0.0
30656,0.000,0.00,0.000,0.00,0.0000,0.0000,0.0000,53901.9645,0.000,0.000,...,3.916763e+06,0.0,1315696.120,0.0000,0.0,0.0,2066143.188,0.0,0.0,0.0

In [19]:
quant1=quant0.where(quant0==0.0,1)
quant1.head()

,07 Nrep,07 Nnes,07 Nrxs,07 Nsto,07 Ntab,08 Nglu,10 Nben,10 Ncle,10 Ngla,10 Nnes,...,-Ncle03-Caly,Solvent_RA1,-Nben03-Caly,Solvent_RA2,Solvent_RA3,Solvent_RA4,-Natt03-Caly,Solvent_RA5,Solvent_RA26,Solvent_RA7
row ID,,,,,,,,,,,,,,,,,,,,,
1465,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11687,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23160,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13348,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
30656,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [31]:
quant1.to_csv("feature-bin.csv",sep=',')
#nrep=quant1[["07 Nrep"]]
#nrep.head()

In [21]:
#rslt_df = nrep[nrep["07 Nrep"] > 0]
#rslt_df.head()

In [22]:
#test = rslt_df.join(x, how="inner")
#test.head()

In [23]:
#allsum=test.sum(axis=0)

In [24]:
#allsum.head()

In [25]:
headers=quant1.columns.values.tolist()
listindex=x.columns.values.tolist()
#fullindex=headers+listindex
print(headers)

['07 Nrep', '07 Nnes', '07 Nrxs', '07 Nsto', '07 Ntab', '08 Nglu', '10 Nben', '10 Ncle', '10 Ngla', '10 Nnes', '10 Ngoo', '10 Nnat', '10 Nnud', '10 Nobt', '10 Nrep', '10 Npal', '10 Npan', '10 Nplu', '10 Nrus02mf', '10 Nsto', '10 Nrus', '10 Nset', '10 Nwut', '10 Nsyl', '10 Sol_', 'Nsto03-Root_', '1-10 Sol_', 'Nrep03-Root_', 'Nnes03-Root_', 'Nsyl03-Root_', 'Nobt03-Root_', 'Nnud03-Root_', 'Nglu03-Root_', 'Nrxs03-Root_', 'Nwut03-Root_', '-Npal03-Root', '-Npan03-Root', '-Ngoo03-Root', '-Nset03-Root', '-Nrus03-Root', '-Ntab03-Root', '-Ncle03-Root', '-Ngla03-Root', '-Nplu03-Root', '-Natt03-Root', '-Nben03-Root', '-Nrep03-MeJ_', '-Nsto03-MeJ_', '-Nsyl03-MeJ_', '-Nnes03-MeJ_', '-Nnud03-MeJ_', '-Nrxs03-MeJ_', '-Nobt03-MeJ_', '-Nwut03-MeJ_', '-Npan03-MeJ_', '-Ngoo03-MeJ_', '-Nglu03-MeJ_', '-Npal03-MeJ_', '-Nset03-MeJ_', '-Nrus03-MeJ_', '-Ntab03-MeJ_', '-Ngla03-MeJ_', '-Nplu03-MeJ_', '-Ncle03-MeJ_', '-Nben03-MeJ_', '-Nrep03-Ctrl', '-Natt03-MeJ_', '-Nsyl03-Ctrl', '-Nsto03-Ctrl', '-Nnes03-Ctrl', '-Nnud03-Ctrl', '-Nobt03-Ctrl', '-Nglu03-Ctrl', '-Nwut03-Ctrl', '-Nrxs03-Ctrl', '-Ngoo03-Ctrl', '-Npan03-Ctrl', '-Nrus03-Ctrl', '-Ntab03-Ctrl', '-Npal03-Ctrl', '-Ngla03-Ctrl', '-Ncle03-Ctrl', '-Nplu03-Ctrl', '-Nset03-Ctrl', '-Nben03-Ctrl', '-Nsto03-Caly', '-Natt03-Ctrl', '-Nrep03-Caly', '-Nnes03-Caly', '-Nsyl03-Caly', '-Nnud03-Caly', '-Nobt03-Caly', '-Nrxs03-Caly', '-Nglu03-Caly', '-Nwut03-Caly', '-Npan03-Caly', '-Npal03-Caly', '-Ngoo03-Caly', '-Nrus03-Caly', '-Ngla03-Caly', '-Ntab03-Caly', '-Nplu03-Caly', '-Ncle03-Caly', 'Solvent_RA1', '-Nben03-Caly', 'Solvent_RA2', 'Solvent_RA3', 'Solvent_RA4', '-Natt03-Caly', 'Solvent_RA5', 'Solvent_RA26', 'Solvent_RA7']

In [26]:
kwargs = {}
for i in headers:
    fsamples=quant1[[i]] #retrieve one sample
    fsamples = fsamples[fsamples[i] > 0] # remove zero occurences of features
    fmotifs = fsamples.join(x, how="inner") # merge with motifs, but only the ones present
    allsums=fmotifs.sum(axis=0)
    kwargs[i] = allsums

#print(kwargs)

In [27]:
#type(kwargs['07 Nrep'])

In [27]:
df3 = pd.DataFrame(kwargs, index=listindex )

df4 =pd.DataFrame(kwargs, index=headers )
"""
df2 = pd.DataFrame(columns=headers)
for i in headers:
    df1=kwargs[i].to_frame()
    df2.join(df1, how="outer")
    
df2.head()
"""

'\ndf2 = pd.DataFrame(columns=headers)\nfor i in headers:\n    df1=kwargs[i].to_frame()\n    df2.join(df1, how="outer")\n    \ndf2.head()\n'

In [30]:

#liste=["a","b","c"]
#df3 = pd.DataFrame( index=listindex )
#df(3) = pd.DataFrame(columns = ['Name', 'Articles', 'Improved'], 
                   #index = ['a', 'b', 'c'])
#df3.columns=liste
df3.head()

,07 Nrep,07 Nnes,07 Nrxs,07 Nsto,07 Ntab,08 Nglu,10 Nben,10 Ncle,10 Ngla,10 Nnes,...,-Ncle03-Caly,Solvent_RA1,-Nben03-Caly,Solvent_RA2,Solvent_RA3,Solvent_RA4,-Natt03-Caly,Solvent_RA5,Solvent_RA26,Solvent_RA7
Motif_StrepSalini_motif_10.m2m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Motif_StrepSalini_motif_105.m2m,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Motif_StrepSalini_motif_106.m2m,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Motif_StrepSalini_motif_108.m2m,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
Motif_StrepSalini_motif_110.m2m,1.0,0.0,0.0,1.0,8.0,0.0,24.0,8.0,9.0,0.0,...,0.0,0.0,12.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [30]:
df3.to_csv("alltissues15072021_counts-motif.csv",sep=',')

In [31]:
df4.fillna(0,inplace=True)
ds=df4.sum(axis=0)
ds.to_csv("alltissues15072021_counts-samples.csv",sep=',')