In [1]:
import pandas as pd
import numpy as np


df_quant = pd.read_csv("/Users/delser/Desktop/PhD/Phytochemistry/FBMN/alltissues/FEATURE-BASED-MOLECULAR-NETWORKING-cf822b6c-15072021/alltissues15072021-quant-py-dil.csv",index_col='row ID', sep=",") # mzmine quant table

In [2]:
df_quant

,row m/z,row retention time,07 Nrep,07 Nnes,07 Nrxs,07 Nsto,07 Ntab,08 Nglu,10 Nben,10 Ncle,...,-Ncle03-Caly,Solvent_RA1,-Nben03-Caly,Solvent_RA2,Solvent_RA3,Solvent_RA4,-Natt03-Caly,Solvent_RA5,Solvent_RA26,Solvent_RA7
row ID,,,,,,,,,,,,,,,,,,,,,
1465,98.961427,46.090285,1912255.595,1819513.95,193807.138,1134014.55,225382.0585,169589.5770,128196.2975,87604.5795,...,0.000000e+00,569.1535,249.555,0.0000,885.5805,656.0620,8.086200e+02,0.0000,263.604,134.2345
11687,105.069960,1.335580,2979.690,0.00,399.556,0.00,1295.0300,0.0000,139611.8360,130091.3065,...,0.000000e+00,0.0000,1368.220,0.0000,1294.2630,4001.5840,2.439269e+03,1378.2065,0.000,342.2805
23160,105.069976,1.476290,0.000,1289.97,599.280,0.00,780.6560,338.1000,1953.2210,2100.7460,...,8.149567e+05,0.0000,2656672.966,154.5080,792.4800,0.0000,1.003830e+06,795.6285,152.646,699.4875
13348,117.057295,0.636114,0.000,804.72,0.000,4006.46,18954.3080,37212.5555,173275.2150,421706.8330,...,2.044090e+06,0.0000,1737524.104,12516.2695,2254.5635,2145.2640,1.358149e+06,0.0000,9782.190,5743.9425
30656,117.057306,0.839741,0.000,0.00,0.000,0.00,999.4080,536.3860,5039.4610,53901.9645,...,3.916763e+06,0.0000,1315696.120,3870.7565,2773.6960,3490.2665,2.066143e+06,2644.5225,3030.446,1771.9900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24054,1430.721213,34.435048,0.000,0.00,0.000,0.00,6286.9545,0.0000,0.0000,5802.2190,...,1.475248e+03,0.0000,0.000,0.0000,0.0000,0.0000,0.000000e+00,0.0000,0.000,0.0000
13546,1430.721947,34.060064,0.000,0.00,0.000,0.00,0.0000,0.0000,0.0000,589619.7345,...,1.610320e+05,0.0000,0.000,0.0000,0.0000,0.0000,0.000000e+00,0.0000,0.000,0.0000
15535,1430.722023,34.364866,0.000,0.00,0.000,0.00,0.0000,0.0000,0.0000,3771.0110,...,7.933500e+02,0.0000,0.000,0.0000,0.0000,0.0000,1.788020e+02,0.0000,0.000,0.0000
14344,1435.675877,34.239693,0.000,0.00,0.000,0.00,0.0000,0.0000,0.0000,74666.5180,...,4.350744e+03,0.0000,0.000,98.3280,0.0000,0.0000,0.000000e+00,82.2780,0.000,0.0000
13731,1458.753099,35.250299,0.000,0.00,0.000,0.00,0.0000,122.4720,0.0000,197619.4325,...,4.086368e+04,0.0000,0.000,0.0000,0.0000,0.0000,0.000000e+00,0.0000,0.000,0.0000

In [3]:
empty=[]

In [4]:
from skbio.diversity import alpha_diversity
df_nrep=df_quant[["07 Nrep","Nrep03-Root_","-Nrep03-MeJ_","-Nrep03-Ctrl","-Nrep03-Caly"]].astype('int')
df_nrep_t=df_nrep.T
counts=df_nrep_t.to_numpy()
ids=["07 Nrep","Nrep03-Root_","-Nrep03-MeJ_","-Nrep03-Ctrl","-Nrep03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [5]:
from skbio.diversity import alpha_diversity
df_Nnes=df_quant[["07 Nnes","Nnes03-Root_","-Nnes03-MeJ_","-Nnes03-Ctrl","-Nnes03-Caly"]].astype('int')
df_Nnes_t=df_Nnes.T
counts=df_Nnes_t.to_numpy()
ids=["07 Nnes","Nnes03-Root_","-Nnes03-MeJ_","-Nnes03-Ctrl","-Nnes03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [6]:
from skbio.diversity import alpha_diversity
df_Nsto=df_quant[["07 Nsto","Nsto03-Root_","-Nsto03-MeJ_","-Nsto03-Ctrl","-Nsto03-Caly"]].astype('int')
df_Nsto_t=df_Nsto.T
counts=df_Nsto_t.to_numpy()
ids=["07 Nsto","Nsto03-Root_","-Nsto03-MeJ_","-Nsto03-Ctrl","-Nsto03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [7]:
from skbio.diversity import alpha_diversity
df_Nrxs=df_quant[["07 Nrxs","Nrxs03-Root_","-Nrxs03-MeJ_","-Nrxs03-Ctrl","-Nrxs03-Caly"]].astype('int')
df_Nrxs_t=df_Nrxs.T
counts=df_Nrxs_t.to_numpy()
ids=["07 Nrxs","Nrxs03-Root_","-Nrxs03-MeJ_","-Nrxs03-Ctrl","-Nrxs03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [8]:
from skbio.diversity import alpha_diversity
df_Ntab=df_quant[["07 Ntab","-Ntab03-Root","-Ntab03-MeJ_","-Ntab03-Ctrl","-Ntab03-Caly"]].astype('int')
df_Ntab_t=df_Ntab.T
counts=df_Ntab_t.to_numpy()
ids=["07 Ntab","-Ntab03-Root","-Ntab03-MeJ_","-Ntab03-Ctrl","-Ntab03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [9]:
from skbio.diversity import alpha_diversity
df_Nglu=df_quant[["08 Nglu","Nglu03-Root_","-Nglu03-MeJ_","-Nglu03-Ctrl","-Nglu03-Caly"]].astype('int')
df_Nglu_t=df_Nglu.T
counts=df_Nglu_t.to_numpy()
ids=["08 Nglu","Nglu03-Root_","-Nglu03-MeJ_","-Nglu03-Ctrl","-Nglu03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [10]:
from skbio.diversity import alpha_diversity
df_Nben=df_quant[["10 Nben","-Nben03-Root","-Nben03-MeJ_","-Nben03-Ctrl","-Nben03-Caly"]].astype('int')
df_Nben_t=df_Nben.T
counts=df_Nben_t.to_numpy()
ids=["10 Nben","Nben03-Root_","-Nben03-MeJ_","-Nben03-Ctrl","-Nben03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [11]:
from skbio.diversity import alpha_diversity
df_Ncle=df_quant[["10 Ncle","-Ncle03-Root","-Ncle03-MeJ_","-Ncle03-Ctrl","-Ncle03-Caly"]].astype('int')
df_Ncle_t=df_Ncle.T
counts=df_Ncle_t.to_numpy()
ids=["10 Ncle","-Ncle03-Root","-Ncle03-MeJ_","-Ncle03-Ctrl","-Ncle03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [12]:
from skbio.diversity import alpha_diversity
df_Ngla=df_quant[["10 Ngla","-Ngla03-Root","-Ngla03-MeJ_","-Ngla03-Ctrl","-Ngla03-Caly"]].astype('int')
df_Ngla_t=df_Ngla.T
counts=df_Ngla_t.to_numpy()
ids=["10 Ngla","-Ngla03-Root","-Ngla03-MeJ_","-Ngla03-Ctrl","-Ngla03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [13]:
from skbio.diversity import alpha_diversity
df_Ngoo=df_quant[["10 Ngoo","-Ngoo03-Root","-Ngoo03-MeJ_","-Ngoo03-Ctrl","-Ngoo03-Caly"]].astype('int')
df_Ngoo_t=df_Ngoo.T
counts=df_Ngoo_t.to_numpy()
ids=["10 Ngoo","-Ngoo03-Root","-Ngoo03-MeJ_","-Ngoo03-Ctrl","-Ngoo03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [14]:
from skbio.diversity import alpha_diversity
df_Natt=df_quant[["10 Nnat","-Natt03-Root","-Natt03-MeJ_","-Natt03-Ctrl","-Natt03-Caly"]].astype('int')
df_Natt_t=df_Natt.T
counts=df_Natt_t.to_numpy()
ids=["10 Nnat","-Natt03-Root","-Natt03-MeJ_","-Natt03-Ctrl","-Natt03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [15]:
from skbio.diversity import alpha_diversity
df_Nnud=df_quant[["10 Nnud","Nnud03-Root_","-Nnud03-MeJ_","-Nnud03-Ctrl","-Nnud03-Caly"]].astype('int')
df_Nnud_t=df_Nnud.T
counts=df_Nnud_t.to_numpy()
ids=["10 Nnud","Nnud03-Root_","-Nnud03-MeJ_","-Nnud03-Ctrl","-Nnud03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [16]:
from skbio.diversity import alpha_diversity
df_Nobt=df_quant[["10 Nobt","Nobt03-Root_","-Nobt03-MeJ_","-Nobt03-Ctrl","-Nobt03-Caly"]].astype('int')
df_Nobt_t=df_Nobt.T
counts=df_Nobt_t.to_numpy()
ids=["10 Nobt","Nobt03-Root_","-Nobt03-MeJ_","-Nobt03-Ctrl","-Nobt03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [17]:
from skbio.diversity import alpha_diversity
df_Npal=df_quant[["10 Npal","-Npal03-Root","-Npal03-MeJ_","-Npal03-Ctrl","-Npal03-Caly"]].astype('int')
df_Npal_t=df_Npal.T
counts=df_Npal_t.to_numpy()
ids=["10 Npal","Npal03-Root_","-Npal03-MeJ_","-Npal03-Ctrl","-Npal03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [18]:
from skbio.diversity import alpha_diversity
df_Npan=df_quant[["10 Npan","-Npan03-Root","-Npan03-MeJ_","-Npan03-Ctrl","-Npan03-Caly"]].astype('int')
df_Npan_t=df_Npan.T
counts=df_Npan_t.to_numpy()
ids=["10 Npan","-Npan03-Root","-Npan03-MeJ_","-Npan03-Ctrl","-Npan03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [19]:
from skbio.diversity import alpha_diversity
df_Nplu=df_quant[["10 Nplu","-Nplu03-Root","-Nplu03-MeJ_","-Nplu03-Ctrl","-Nplu03-Caly"]].astype('int')
df_Nplu_t=df_Nplu.T
counts=df_Nplu_t.to_numpy()
ids=["10 Nplu","-Nplu03-Root","-Nplu03-MeJ_","-Nplu03-Ctrl","-Nplu03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [20]:
from skbio.diversity import alpha_diversity
df_Nrus=df_quant[["10 Nrus","-Nrus03-Root","-Nrus03-MeJ_","-Nrus03-Ctrl","-Nrus03-Caly","10 Nrus02mf"]].astype('int')
df_Nrus_t=df_Nrus.T
counts=df_Nrus_t.to_numpy()
ids=["10 Nrus","-Nrus03-Root","-Nrus03-MeJ_","-Nrus03-Ctrl","-Nrus03-Caly","10 Nrus02mf"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [21]:
from skbio.diversity import alpha_diversity
df_Nset=df_quant[["10 Nset","-Nset03-Root","-Nset03-MeJ_","-Nset03-Ctrl"]].astype('int')
df_Nset_t=df_Nset.T
counts=df_Nset_t.to_numpy()
ids=["10 Nset","-Nset03-Root","-Nset03-MeJ_","-Nset03-Ctrl"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [22]:
from skbio.diversity import alpha_diversity
df_Nwut=df_quant[["10 Nwut","Nwut03-Root_","-Nwut03-MeJ_","-Nwut03-Ctrl","-Nwut03-Caly"]].astype('int')
df_Nwut_t=df_Nwut.T
counts=df_Nwut_t.to_numpy()
ids=["10 Nwut","Nwut03-Root_","-Nwut03-MeJ_","-Nwut03-Ctrl","-Nwut03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [23]:
from skbio.diversity import alpha_diversity
df_Nsyl=df_quant[["10 Nsyl","Nsyl03-Root_","-Nsyl03-MeJ_","-Nsyl03-Ctrl","-Nsyl03-Caly"]].astype('int')
df_Nsyl_t=df_Nsyl.T
counts=df_Nsyl_t.to_numpy()
ids=["10 Nsyl","Nsyl03-Root_","-Nsyl03-MeJ_","-Nsyl03-Ctrl","-Nsyl03-Caly"]
adiv_obs_otus = alpha_diversity('shannon', counts, ids)
empty.append(adiv_obs_otus)
adiv_obs_otus
adiv_obs_otus = alpha_diversity('observed_otus', counts, ids)
empty.append(adiv_obs_otus)

In [24]:
x=pd.concat(empty, axis=0, ignore_index=False)
x

07 Nrep            3.724988
Nrep03-Root_       7.655595
-Nrep03-MeJ_       9.061189
-Nrep03-Ctrl       8.876655
-Nrep03-Caly       8.758468
                   ...
10 Nsyl         6540.000000
Nsyl03-Root_    7022.000000
-Nsyl03-MeJ_    8942.000000
-Nsyl03-Ctrl    8482.000000
-Nsyl03-Caly    9364.000000
Length: 200, dtype: float64

In [25]:
x.to_csv("alpha_diversity_nicotiana.tsv",sep="\t")